
host = 'localhost'
database = 'DBS'
user = 'postgres'
password = 'konstantynopol'

formatter = {"identyfikator": "Identyfikator",
             "nazwa": "Nazwa",
             "rodzaj": "Rodzaj",
             "miasto": "Miasto",
             "oznaczenie": "Oznaczenie",
             "liczba_personelu": "Liczba personelu",
             "rola_budynku": "Rola",
             "id_jednostki": "Identyfikator jednostki",
             "PESEL": "PESEL",
             "imie": "Imię",
             "nazwisko": "Nazwisko",
             "data_ur": "Data urodzenia",
             "grupa_krwi": "Grupa krwi",
             "wyznanie": "Wyznanie",
             "budynek": "Budynek",
             "ranga": "Ranga",
             "numer_seryjny": "Numer seryjny",
             "typ": "Typ",
             "producent": "Producent",
             "model": "Model",
             "data_produkcji": "Data produkcji",
             "ilosc": "Ilość",
             "data_waznosci": "Data ważności",
             "id_zamowienia": "Numer zamówienia",
             "id_pojazdu": "ID pojazdu",
             "masa": "Masa",
             "liczba_zalogi": "Liczba członków załogi",
             "zasieg": "Zasięg",
             "status": "Status",
             "rok_produkcji": "Rok produkcji",
             "rejestracja": "Rejestracja",
             "data_od": "Data rozpoczęcia",
             "data_do": "Data zakończenia",
             "pesel_oficera": "PESEL oficera",
             "nazwa_rangi": "Nazwa",
             "liczba_przepustek": "Liczba przepustek",
             "poziom_upr": "Poziom uprawnień",
             "zold": "Żołd",
             "koszt": "Koszt",
             "data_zam": "Data złożenia zamówienia",
             "deadline": "Maksymalny termin realizacji"
             }